//! Linux `KEY_*` (evdev) ↔ [`KeyName`].

use evdev::KeyCode;
use keys_layer_core::KeyName;

pub fn keycode_to_name(code: KeyCode) -> Option<KeyName> {
    let name = match code {
        KeyCode::KEY_A => "a",
        KeyCode::KEY_B => "b",
        KeyCode::KEY_C => "c",
        KeyCode::KEY_D => "d",
        KeyCode::KEY_E => "e",
        KeyCode::KEY_F => "f",
        KeyCode::KEY_G => "g",
        KeyCode::KEY_H => "h",
        KeyCode::KEY_I => "i",
        KeyCode::KEY_J => "j",
        KeyCode::KEY_K => "k",
        KeyCode::KEY_L => "l",
        KeyCode::KEY_M => "m",
        KeyCode::KEY_N => "n",
        KeyCode::KEY_O => "o",
        KeyCode::KEY_P => "p",
        KeyCode::KEY_Q => "q",
        KeyCode::KEY_R => "r",
        KeyCode::KEY_S => "s",
        KeyCode::KEY_T => "t",
        KeyCode::KEY_U => "u",
        KeyCode::KEY_V => "v",
        KeyCode::KEY_W => "w",
        KeyCode::KEY_X => "x",
        KeyCode::KEY_Y => "y",
        KeyCode::KEY_Z => "z",
        KeyCode::KEY_1 => "1",
        KeyCode::KEY_2 => "2",
        KeyCode::KEY_3 => "3",
        KeyCode::KEY_4 => "4",
        KeyCode::KEY_5 => "5",
        KeyCode::KEY_6 => "6",
        KeyCode::KEY_7 => "7",
        KeyCode::KEY_8 => "8",
        KeyCode::KEY_9 => "9",
        KeyCode::KEY_0 => "0",
        KeyCode::KEY_ENTER => "enter",
        KeyCode::KEY_ESC => "escape",
        KeyCode::KEY_BACKSPACE => "delete",
        KeyCode::KEY_TAB => "tab",
        KeyCode::KEY_SPACE => "space",
        KeyCode::KEY_MINUS => "minus",
        KeyCode::KEY_EQUAL => "equal",
        KeyCode::KEY_LEFTBRACE => "left_bracket",
        KeyCode::KEY_RIGHTBRACE => "right_bracket",
        KeyCode::KEY_BACKSLASH => "backslash",
        KeyCode::KEY_SEMICOLON => "semicolon",
        KeyCode::KEY_APOSTROPHE => "quote",
        KeyCode::KEY_GRAVE => "grave",
        KeyCode::KEY_COMMA => "comma",
        KeyCode::KEY_DOT => "period",
        KeyCode::KEY_SLASH => "slash",
        KeyCode::KEY_CAPSLOCK => "caps_lock",
        KeyCode::KEY_F1 => "f1",
        KeyCode::KEY_F2 => "f2",
        KeyCode::KEY_F3 => "f3",
        KeyCode::KEY_F4 => "f4",
        KeyCode::KEY_F5 => "f5",
        KeyCode::KEY_F6 => "f6",
        KeyCode::KEY_F7 => "f7",
        KeyCode::KEY_F8 => "f8",
        KeyCode::KEY_F9 => "f9",
        KeyCode::KEY_F10 => "f10",
        KeyCode::KEY_F11 => "f11",
        KeyCode::KEY_F12 => "f12",
        KeyCode::KEY_INSERT => "insert",
        KeyCode::KEY_HOME => "home",
        KeyCode::KEY_PAGEUP => "page_up",
        KeyCode::KEY_DELETE => "forward_delete",
        KeyCode::KEY_END => "end",
        KeyCode::KEY_PAGEDOWN => "page_down",
        KeyCode::KEY_RIGHT => "right",
        KeyCode::KEY_LEFT => "left",
        KeyCode::KEY_DOWN => "down",
        KeyCode::KEY_UP => "up",
        KeyCode::KEY_LEFTCTRL => "left_control",
        KeyCode::KEY_LEFTSHIFT => "left_shift",
        KeyCode::KEY_LEFTALT => "left_alt",
        KeyCode::KEY_LEFTMETA => "left_meta",
        KeyCode::KEY_RIGHTCTRL => "right_control",
        KeyCode::KEY_RIGHTSHIFT => "right_shift",
        KeyCode::KEY_RIGHTALT => "right_alt",
        KeyCode::KEY_RIGHTMETA => "right_meta",
        KeyCode::KEY_102ND => "non_us_backslash",
        _ => return None,
    };
    Some(KeyName::new(name))
}

pub fn name_to_keycode(name: &KeyName) -> Option<KeyCode> {
    Some(match name.as_str() {
        "a" => KeyCode::KEY_A,
        "b" => KeyCode::KEY_B,
        "c" => KeyCode::KEY_C,
        "d" => KeyCode::KEY_D,
        "e" => KeyCode::KEY_E,
        "f" => KeyCode::KEY_F,
        "g" => KeyCode::KEY_G,
        "h" => KeyCode::KEY_H,
        "i" => KeyCode::KEY_I,
        "j" => KeyCode::KEY_J,
        "k" => KeyCode::KEY_K,
        "l" => KeyCode::KEY_L,
        "m" => KeyCode::KEY_M,
        "n" => KeyCode::KEY_N,
        "o" => KeyCode::KEY_O,
        "p" => KeyCode::KEY_P,
        "q" => KeyCode::KEY_Q,
        "r" => KeyCode::KEY_R,
        "s" => KeyCode::KEY_S,
        "t" => KeyCode::KEY_T,
        "u" => KeyCode::KEY_U,
        "v" => KeyCode::KEY_V,
        "w" => KeyCode::KEY_W,
        "x" => KeyCode::KEY_X,
        "y" => KeyCode::KEY_Y,
        "z" => KeyCode::KEY_Z,
        "1" => KeyCode::KEY_1,
        "2" => KeyCode::KEY_2,
        "3" => KeyCode::KEY_3,
        "4" => KeyCode::KEY_4,
        "5" => KeyCode::KEY_5,
        "6" => KeyCode::KEY_6,
        "7" => KeyCode::KEY_7,
        "8" => KeyCode::KEY_8,
        "9" => KeyCode::KEY_9,
        "0" => KeyCode::KEY_0,
        "enter" | "return" => KeyCode::KEY_ENTER,
        "escape" => KeyCode::KEY_ESC,
        "delete" | "backspace" => KeyCode::KEY_BACKSPACE,
        "tab" => KeyCode::KEY_TAB,
        "space" => KeyCode::KEY_SPACE,
        "minus" | "-" => KeyCode::KEY_MINUS,
        "equal" | "=" => KeyCode::KEY_EQUAL,
        "left_bracket" | "[" => KeyCode::KEY_LEFTBRACE,
        "right_bracket" | "]" => KeyCode::KEY_RIGHTBRACE,
        "backslash" | "\\" => KeyCode::KEY_BACKSLASH,
        "semicolon" | ";" => KeyCode::KEY_SEMICOLON,
        "quote" | "'" => KeyCode::KEY_APOSTROPHE,
        "grave" | "`" => KeyCode::KEY_GRAVE,
        "comma" | "," => KeyCode::KEY_COMMA,
        "period" | "." => KeyCode::KEY_DOT,
        "slash" | "/" => KeyCode::KEY_SLASH,
        "caps_lock" | "caps" => KeyCode::KEY_CAPSLOCK,
        "f1" => KeyCode::KEY_F1,
        "f2" => KeyCode::KEY_F2,
        "f3" => KeyCode::KEY_F3,
        "f4" => KeyCode::KEY_F4,
        "f5" => KeyCode::KEY_F5,
        "f6" => KeyCode::KEY_F6,
        "f7" => KeyCode::KEY_F7,
        "f8" => KeyCode::KEY_F8,
        "f9" => KeyCode::KEY_F9,
        "f10" => KeyCode::KEY_F10,
        "f11" => KeyCode::KEY_F11,
        "f12" => KeyCode::KEY_F12,
        "insert" => KeyCode::KEY_INSERT,
        "home" => KeyCode::KEY_HOME,
        "page_up" => KeyCode::KEY_PAGEUP,
        "forward_delete" => KeyCode::KEY_DELETE,
        "end" => KeyCode::KEY_END,
        "page_down" => KeyCode::KEY_PAGEDOWN,
        "right" => KeyCode::KEY_RIGHT,
        "left" => KeyCode::KEY_LEFT,
        "down" => KeyCode::KEY_DOWN,
        "up" => KeyCode::KEY_UP,
        "left_control" => KeyCode::KEY_LEFTCTRL,
        "left_shift" => KeyCode::KEY_LEFTSHIFT,
        "left_alt" => KeyCode::KEY_LEFTALT,
        "left_meta" => KeyCode::KEY_LEFTMETA,
        "right_control" => KeyCode::KEY_RIGHTCTRL,
        "right_shift" => KeyCode::KEY_RIGHTSHIFT,
        "right_alt" => KeyCode::KEY_RIGHTALT,
        "right_meta" => KeyCode::KEY_RIGHTMETA,
        "non_us_backslash" | "nubs" => KeyCode::KEY_102ND,
        _ => return None,
    })
}

/// Key codes our virtual keyboard advertises.
pub fn all_output_keycodes() -> Vec<KeyCode> {
    [
        KeyCode::KEY_A,
        KeyCode::KEY_B,
        KeyCode::KEY_C,
        KeyCode::KEY_D,
        KeyCode::KEY_E,
        KeyCode::KEY_F,
        KeyCode::KEY_G,
        KeyCode::KEY_H,
        KeyCode::KEY_I,
        KeyCode::KEY_J,
        KeyCode::KEY_K,
        KeyCode::KEY_L,
        KeyCode::KEY_M,
        KeyCode::KEY_N,
        KeyCode::KEY_O,
        KeyCode::KEY_P,
        KeyCode::KEY_Q,
        KeyCode::KEY_R,
        KeyCode::KEY_S,
        KeyCode::KEY_T,
        KeyCode::KEY_U,
        KeyCode::KEY_V,
        KeyCode::KEY_W,
        KeyCode::KEY_X,
        KeyCode::KEY_Y,
        KeyCode::KEY_Z,
        KeyCode::KEY_1,
        KeyCode::KEY_2,
        KeyCode::KEY_3,
        KeyCode::KEY_4,
        KeyCode::KEY_5,
        KeyCode::KEY_6,
        KeyCode::KEY_7,
        KeyCode::KEY_8,
        KeyCode::KEY_9,
        KeyCode::KEY_0,
        KeyCode::KEY_ENTER,
        KeyCode::KEY_ESC,
        KeyCode::KEY_BACKSPACE,
        KeyCode::KEY_TAB,
        KeyCode::KEY_SPACE,
        KeyCode::KEY_MINUS,
        KeyCode::KEY_EQUAL,
        KeyCode::KEY_LEFTBRACE,
        KeyCode::KEY_RIGHTBRACE,
        KeyCode::KEY_BACKSLASH,
        KeyCode::KEY_SEMICOLON,
        KeyCode::KEY_APOSTROPHE,
        KeyCode::KEY_GRAVE,
        KeyCode::KEY_COMMA,
        KeyCode::KEY_DOT,
        KeyCode::KEY_SLASH,
        KeyCode::KEY_CAPSLOCK,
        KeyCode::KEY_F1,
        KeyCode::KEY_F2,
        KeyCode::KEY_F3,
        KeyCode::KEY_F4,
        KeyCode::KEY_F5,
        KeyCode::KEY_F6,
        KeyCode::KEY_F7,
        KeyCode::KEY_F8,
        KeyCode::KEY_F9,
        KeyCode::KEY_F10,
        KeyCode::KEY_F11,
        KeyCode::KEY_F12,
        KeyCode::KEY_INSERT,
        KeyCode::KEY_HOME,
        KeyCode::KEY_PAGEUP,
        KeyCode::KEY_DELETE,
        KeyCode::KEY_END,
        KeyCode::KEY_PAGEDOWN,
        KeyCode::KEY_RIGHT,
        KeyCode::KEY_LEFT,
        KeyCode::KEY_DOWN,
        KeyCode::KEY_UP,
        KeyCode::KEY_LEFTCTRL,
        KeyCode::KEY_LEFTSHIFT,
        KeyCode::KEY_LEFTALT,
        KeyCode::KEY_LEFTMETA,
        KeyCode::KEY_RIGHTCTRL,
        KeyCode::KEY_RIGHTSHIFT,
        KeyCode::KEY_RIGHTALT,
        KeyCode::KEY_RIGHTMETA,
        KeyCode::KEY_102ND,
        // Multimedia (F-row media mode)
        KeyCode::KEY_MUTE,
        KeyCode::KEY_VOLUMEDOWN,
        KeyCode::KEY_VOLUMEUP,
        KeyCode::KEY_PREVIOUSSONG,
        KeyCode::KEY_PLAYPAUSE,
        KeyCode::KEY_NEXTSONG,
        KeyCode::KEY_BRIGHTNESSDOWN,
        KeyCode::KEY_BRIGHTNESSUP,
        KeyCode::KEY_KBDILLUMDOWN,
        KeyCode::KEY_KBDILLUMUP,
        KeyCode::KEY_FN,
    ]
    .to_vec()
}
